# Generated by Django 5.1.6 on 2025-03-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ussdreport',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='ussdreport',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='ussdreport',
            name='open_space',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='ussdreport',
            name='reference_number',
            field=models.CharField(default='unknown', max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='ussdreport',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
