# Generated by Django 5.1.7 on 2025-04-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0002_remove_ussdreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdreport',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
