# Generated by Django 5.1.7 on 2025-08-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('ward_executive', 'Ward Executive'), ('village_chairman', 'Village Chairman'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
