# Generated by Django 5.1.7 on 2025-08-04 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openspace',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openspaces', to='myapp.street'),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openspaces', to='myapp.ward'),
        ),
    ]
