# Generated by Django 5.1.7 on 2025-08-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_openspace_street_alter_openspace_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
