# Generated by Django 5.1.6 on 2025-02-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_delete_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
