# Generated by Django 5.1.7 on 2025-08-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_report_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.street'),
        ),
    ]
