# Generated by Django 5.1.6 on 2025-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('district', models.CharField(choices=[('Kinondoni', 'Kinondoni'), ('Ilala', 'Ilala'), ('Ubungo', 'Ubungo'), ('Temeke', 'Temeke'), ('Kigamboni', 'Kigamboni')], max_length=255)),
            ],
        ),
    ]
