# Generated by Django 5.1.6 on 2025-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_openspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspace',
            name='district',
            field=models.CharField(choices=[('Kinondoni', 'Kinondoni'), ('Ilala', 'Ilala'), ('Ubungo', 'Ubungo'), ('Temeke', 'Temeke'), ('Kigamboni', 'Kigamboni')], max_length=50),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
