# Generated by Django 5.1.7 on 2025-08-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_report_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='street',
        ),
        migrations.AddField(
            model_name='report',
            name='street_name_backup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
