# Generated by Django 5.1.7 on 2025-08-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_report_street_report_street_name_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
