# Generated by Django 5.1.6 on 2025-03-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_openspace_created_at_alter_openspace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspace',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
