# Generated by Django 5.1.7 on 2025-08-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_report_forwarded_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='forwarded_to',
        ),
    ]
