# Generated by Django 5.1.6 on 2025-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_openspace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='openspace',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
