# Generated by Django 5.1.7 on 2025-08-14 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_reportreplyvillageexecutive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportForwardToadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('forwarded_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_forwarded_to_admin', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards_to_admin', to='myapp.report')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received_by_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
