# Generated by Django 5.1.7 on 2025-08-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_reportforwardtoadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportforwardtoadmin',
            name='message',
        ),
    ]
