# Generated by Django 5.1.6 on 2025-03-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_report_latitude_report_longitude_report_space_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
