# Generated by Django 5.1.7 on 2025-08-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_reportforwardtoadmin_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportforwardtoadmin',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
