# Generated by Django 5.1.6 on 2025-03-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_reporthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporthistory',
            old_name='file_path',
            new_name='file',
        ),
    ]
