# Generated by Django 5.1.7 on 2025-08-18 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_reportforwardtoadmin_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='myapp.street'),
        ),
    ]
