# Generated by Django 5.1.6 on 2025-03-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_file_path_reporthistory_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthistory',
            name='report_id',
            field=models.CharField(default='RFSGSSCX', max_length=8, unique=True),
        ),
    ]
