# Generated by Django 5.1.6 on 2025-03-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_reporthistory_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthistory',
            name='report_id',
            field=models.CharField(default='RFSGSSCX', max_length=8),
        ),
    ]
