# Generated by Django 5.1.7 on 2025-08-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_report_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
