# Generated by Django 5.1.7 on 2025-08-28 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_report_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportforward',
            name='message',
        ),
        migrations.RemoveField(
            model_name='reportreply',
            name='sender',
        ),
        migrations.AddField(
            model_name='reportreply',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
