# Generated by Django 5.1.6 on 2025-03-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_reporthistory_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporthistory',
            name='report_id',
        ),
    ]
