# Generated by Django 5.1.6 on 2025-03-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_reporthistory_report_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporthistory',
            old_name='confirmed_at',
            new_name='created_at',
        ),
    ]
