# Generated by Django 5.1.6 on 2025-03-21 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_confirmed_at_reporthistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='session_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
