# Generated by Django 5.1.6 on 2025-03-22 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_report_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthistory',
            name='session_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
