# Generated by Django 5.1.6 on 2025-03-24 05:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_reporthistory_user_alter_reporthistory_session_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporthistory',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, null=True, blank=True),
            preserve_default=False,
        ),
    ]
