# Generated by Django 5.1.6 on 2025-03-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_report_session_id_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='session_id',
            field=models.CharField(default='rsfsdjhscxz', max_length=255),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='session_id',
            field=models.CharField(default='gscsfxgxgxzz', max_length=255),
        ),
    ]
