# Generated by Django 5.1.6 on 2025-03-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_report_user_report_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporthistory',
            name='user',
        ),
    ]
