# Generated by Django 5.1.6 on 2025-03-24 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_reporthistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthistory',
            name='report_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=8),
            preserve_default=False,
        ),
    ]
