# Generated by Django 5.1.6 on 2025-03-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_ussdreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UssdReport',
        ),
    ]
