# Generated by Django 5.1.7 on 2025-03-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_delete_ussdreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthistory',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
